---
# prometheus_node_exporter/tasks/main.yml

- name: 'Install the package'
  package:
    name: 'golang-github-prometheus-prometheus'
    state: 'present'

- name: 'Start and enable the service'
  service:
    name: 'prometheus-node_exporter.service'
    state: 'started'
    enabled: 'true'
